server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/microservices
    username: postgres
    password: admin
#    driver.class-name: com.postgresql.jdbc.Driver

  application:
    name: HOTELSERVICE

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#    This dialect detected automatically, so no need to explicitly add config for that
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect

  config:
    import: optional:configserver:http://localhost:8085/

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka
