server:
  port: 8085

spring:
  application:
    name: CONFIGSERVER

  cloud:
    config:
      server:
        git:
          uri: https://github.com/vishal755/HiotelRatingSystem-microservices-configurations
          clone-on-start: true

