server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: root
    driver.class-name: com.mysql.jdbc.Driver

  application:
    name: USERSERVICE

  profile: dev

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#    This dialect detected automatically, so no need to explicitly add config for that
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect

# below properties will fetch config from config server (configuration stored at github repo)
  config:
    import: optional:configserver:http://localhost:8085



#eureka:
#  instance:
#    prefer-ip-address: true #in eureka server page it will use ip address as url for this microservice.
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka