server:
  port: 8083

spring:
  data:
    uri: mongodb://localhost:27017
    database: microservices

  application:
    name: RATINGSERVICE

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka